# Đặt tên cho workflow của bạn
name: Build and Push Docker Image

# Kích hoạt workflow này khi có ai đó push code lên nhánh 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # Chạy trên một máy ảo Ubuntu mới nhất
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy mã nguồn từ repo của bạn
      - name: Check out the repo
        uses: actions/checkout@v4

      # 2. Đăng nhập vào Docker Hub
      # Nó sẽ sử dụng "Secrets" bạn đã thiết lập
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build và Push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            thanhkoy/traffmonetizer-proxy:latest
            thanhkoy/traffmonetizer-proxy:1.0
